<a href="https://colab.research.google.com/github/ananddiv/datascience/blob/main/Ensemble_Bagging_Boosting_Stacking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import pandas as pd
import numpy as np

from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.metrics import classification_report,confusion_matrix

**Bagging Ensemble Model**

In [52]:
url="https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"

In [53]:
name_list = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

In [54]:
df = pd.read_csv(url,names = name_list)
df.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [55]:
df.shape

(768, 9)

In [56]:
df.describe()

preg        plas        pres        skin        test        mass  \
count  768.000000  768.000000  768.000000  768.000000  768.000000  768.000000   
mean     3.845052  120.894531   69.105469   20.536458   79.799479   31.992578   
std      3.369578   31.972618   19.355807   15.952218  115.244002    7.884160   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000   99.000000   62.000000    0.000000    0.000000   27.300000   
50%      3.000000  117.000000   72.000000   23.000000   30.500000   32.000000   
75%      6.000000  140.250000   80.000000   32.000000  127.250000   36.600000   
max     17.000000  199.000000  122.000000   99.000000  846.000000   67.100000   

             pedi         age       class  
count  768.000000  768.000000  768.000000  
mean     0.471876   33.240885    0.348958  
std      0.331329   11.760232    0.476951  
min      0.078000   21.000000    0.000000  
25%      0.243750   24.000000    0.000000  
50%      0.372500   29.000000    0.000000  
75%      0.626250   41.000000    1.000000  
max      2.420000   81.000000    1.000000

In [57]:
X=df.drop('class',axis=1)
y=df['class']

As we are going to use random forest, we need not scale the data

Splitting the data into train/test sets

In [58]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=42)

Use Kfold to split the train data into 5 splits

In [59]:
kfold=KFold(n_splits=5)

In [60]:
tree = DecisionTreeClassifier()

In [61]:
bagger = BaggingClassifier(tree,n_estimators = 50,random_state=42)

In [62]:
bagger.fit(X_train,y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=50,
                  random_state=42)

In [63]:
preds = bagger.predict(X_test)

In [64]:
cv_results = cross_val_score(bagger,X_train,y_train,scoring='accuracy',cv=kfold)
cv_results

array([0.80582524, 0.73786408, 0.7961165 , 0.73786408, 0.78431373])

In [65]:
np.mean(cv_results)

0.7723967256805635

In [66]:
print(classification_report(y_test,preds))
print(confusion_matrix(y_test,preds))

              precision    recall  f1-score   support

           0       0.78      0.80      0.79       168
           1       0.59      0.57      0.58        86

    accuracy                           0.72       254
   macro avg       0.69      0.68      0.69       254
weighted avg       0.72      0.72      0.72       254

[[134  34]
 [ 37  49]]


In [86]:
dia_gbc = GradientBoostingClassifier(learning_rate=0.1)
dia_gbc.fit(X_train,y_train)
preds = dia_gbc.predict(X_test)

In [87]:
dia_gbc.predict_proba(X_test)

array([[8.62720920e-04, 9.99137279e-01],
       [9.99630807e-01, 3.69192869e-04],
       [9.98355986e-01, 1.64401405e-03],
       [4.37465574e-04, 9.99562534e-01],
       [2.55373763e-04, 9.99744626e-01],
       [9.99536029e-01, 4.63970578e-04],
       [9.99608817e-01, 3.91183471e-04],
       [9.81370413e-01, 1.86295873e-02],
       [7.01340882e-01, 2.98659118e-01],
       [9.17435088e-04, 9.99082565e-01],
       [4.33124714e-03, 9.95668753e-01],
       [9.98963594e-01, 1.03640620e-03],
       [2.86728912e-03, 9.97132711e-01],
       [9.67763139e-01, 3.22368607e-02],
       [5.12605192e-04, 9.99487395e-01],
       [9.99471440e-01, 5.28559589e-04],
       [5.53719895e-04, 9.99446280e-01],
       [3.37399868e-04, 9.99662600e-01],
       [5.29010795e-04, 9.99470989e-01],
       [9.99601847e-01, 3.98153448e-04],
       [5.29329803e-03, 9.94706702e-01],
       [4.52111825e-04, 9.99547888e-01],
       [9.99569098e-01, 4.30901921e-04],
       [8.03169975e-04, 9.99196830e-01],
       [7.717618

In [68]:
print(classification_report(y_test,preds))
print(confusion_matrix(y_test,preds))

              precision    recall  f1-score   support

           0       0.81      0.78      0.79       168
           1       0.60      0.64      0.62        86

    accuracy                           0.73       254
   macro avg       0.70      0.71      0.71       254
weighted avg       0.74      0.73      0.73       254

[[131  37]
 [ 31  55]]


**Boosting Ensemble Models**

In [69]:
from sklearn.datasets import load_breast_cancer

import pandas as pd
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier

from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [70]:
df = pd.DataFrame(load_breast_cancer()['data'],columns=load_breast_cancer()['feature_names'])
df['y'] = pd.DataFrame(load_breast_cancer()['target'])
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  y  
0          0.4601                  0.11890  0  
1          0.2750                  0.08902  0  
2          0.3613                  0.08758  0  
3          0.6638                  0.17300  0  
4          0.2364                  0.07678  0  

[5 rows x 31 columns]

In [71]:
df['y'].value_counts()

1    357
0    212
Name: y, dtype: int64

In [72]:
X=df.drop('y',axis=1)
y=df['y']

In [73]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=42)

In [74]:
X_train.shape

(455, 30)

In [75]:
X_test.shape

(114, 30)

In [76]:
gbc = GradientBoostingClassifier(learning_rate=0.1)

In [77]:
gbc.get_params()

{'ccp_alpha': 0.0,
 'criterion': 'friedman_mse',
 'init': None,
 'learning_rate': 0.1,
 'loss': 'log_loss',
 'max_depth': 3,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_iter_no_change': None,
 'random_state': None,
 'subsample': 1.0,
 'tol': 0.0001,
 'validation_fraction': 0.1,
 'verbose': 0,
 'warm_start': False}

In [78]:
gbc.fit(X_train,y_train)

GradientBoostingClassifier()

In [79]:
preds = gbc.predict(X_test)

In [80]:
print(classification_report(y_test,preds))
print(confusion_matrix(y_test,preds))

              precision    recall  f1-score   support

           0       0.95      0.93      0.94        43
           1       0.96      0.97      0.97        71

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114

[[40  3]
 [ 2 69]]


In [83]:
tree = DecisionTreeClassifier()
bagger_gbc = BaggingClassifier(tree,n_estimators = 50,random_state=42)
bagger_gbc.fit(X_train,y_train)
preds = bagger_gbc.predict(X_test)

In [84]:
print(classification_report(y_test,preds))
print(confusion_matrix(y_test,preds))

              precision    recall  f1-score   support

           0       0.95      0.93      0.94        43
           1       0.96      0.97      0.97        71

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114

[[40  3]
 [ 2 69]]


**Stacking Ensemble Models**

In [91]:
pip install vecstack

In [92]:
pip install xgboost

In [93]:
import warnings

import pandas as pd

from xgboost import XGBClassifier
from vecstack import stacking

from sklearn.preprocessing import LabelEncoder
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score, confusion_matrix,classification_report

In [99]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data'
name_list = ['Class', 'Alcohol', 'Malic_acid', 'Ash','Alcalinity_of_ash' ,'Magnesium', 'Total_phenols','Flavanoids',
         'Nonflavanoid_phenols', 'Proanthocyanins', 'Color_intensity', 'Hue', 'OD280/OD315_of_diluted wines','Proline']

In [100]:
df = pd.read_csv(url,names=name_list)
df.head()

Class  Alcohol  Malic_acid   Ash  Alcalinity_of_ash  Magnesium  \
0      1    14.23        1.71  2.43               15.6        127   
1      1    13.20        1.78  2.14               11.2        100   
2      1    13.16        2.36  2.67               18.6        101   
3      1    14.37        1.95  2.50               16.8        113   
4      1    13.24        2.59  2.87               21.0        118   

   Total_phenols  Flavanoids  Nonflavanoid_phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   Color_intensity   Hue  OD280/OD315_of_diluted wines  Proline  
0             5.64  1.04                          3.92     1065  
1             4.38  1.05                          3.40     1050  
2             5.68  1.03                          3.17     1185  
3             7.80  0.86                          3.45     1480  
4             4.32  1.04                          2.93      735

In [101]:
df['Class'].value_counts()

2    71
1    59
3    48
Name: Class, dtype: int64

In [102]:
X=df.iloc[:,1:]
y=df['Class']

In [103]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Alcohol                       178 non-null    float64
 1   Malic_acid                    178 non-null    float64
 2   Ash                           178 non-null    float64
 3   Alcalinity_of_ash             178 non-null    float64
 4   Magnesium                     178 non-null    int64  
 5   Total_phenols                 178 non-null    float64
 6   Flavanoids                    178 non-null    float64
 7   Nonflavanoid_phenols          178 non-null    float64
 8   Proanthocyanins               178 non-null    float64
 9   Color_intensity               178 non-null    float64
 10  Hue                           178 non-null    float64
 11  OD280/OD315_of_diluted wines  178 non-null    float64
 12  Proline                       178 non-null    int64  
dtypes: fl

In [109]:
le=LabelEncoder()
y = le.fit_transform(y)

In [110]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=42)

In [115]:
models = [
    KNeighborsClassifier(),
    RandomForestClassifier(),
    XGBClassifier()
]

Ignore regular user and future warning

In [112]:
warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

In [123]:
S_train,S_test = stacking(models,X_train,y_train,X_test, regression=False,random_state=42, n_folds = 5, shuffle=True, metric=accuracy_score, verbose=2)

task:         [classification]
n_classes:    [3]
metric:       [accuracy_score]
mode:         [oof_pred_bag]
n_models:     [3]

model  0:     [KNeighborsClassifier]
    fold  0:  [0.89655172]
    fold  1:  [0.72413793]
    fold  2:  [0.64285714]
    fold  3:  [0.64285714]
    fold  4:  [0.71428571]
    ----
    MEAN:     [0.72413793] + [0.09277577]
    FULL:     [0.72535211]

model  1:     [RandomForestClassifier]
    fold  0:  [0.93103448]
    fold  1:  [0.96551724]
    fold  2:  [0.96428571]
    fold  3:  [1.00000000]
    fold  4:  [1.00000000]
    ----
    MEAN:     [0.97216749] + [0.02587497]
    FULL:     [0.97183099]

model  2:     [XGBClassifier]
    fold  0:  [0.93103448]
    fold  1:  [0.96551724]
    fold  2:  [0.89285714]
    fold  3:  [0.92857143]
    fold  4:  [0.96428571]
    ----
    MEAN:     [0.93645320] + [0.02687552]
    FULL:     [0.93661972]



Feed the output of the staking algorithem to a 2nd level algorithm/metamodel

In [125]:
svc=SVC(kernel='linear')

In [126]:
svc.fit(S_train,y_train)

SVC(kernel='linear')

In [127]:
preds = svc.predict(S_test)

In [128]:
print(classification_report(y_test,preds))
print(confusion_matrix(y_test,preds))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00         8

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36

[[14  0  0]
 [ 0 14  0]
 [ 0  0  8]]
